- name: "Install repository intallation script."
  template: src=install_repo_wrapper.sh.j2 dest=/usr/bin/install-repository mode=a+x

- name: "Install galaxy user creation script."
  template: src=create_galaxy_user.py.j2 dest=/usr/local/bin/create_galaxy_user.py mode=a+x
