- name: Install web related system packages
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - nodejs-legacy
    - npm
  when: galaxy_extras_install_packages

- name: "Install proxy dependencies."
  shell: "cd {{ galaxy_server_dir }}/lib/galaxy/web/proxy/js && npm install"
  sudo: True
  sudo_user: "{{ galaxy_user_name }}"

- name: "Install IPython container."
  shell: "docker pull {{ galaxy_extras_ie_ipython_image }}"
  sudo: True
  when: galaxy_extras_ie_fetch_ipython

- name: "Install Juypter container."
  shell: "docker pull {{ galaxy_extras_ie_juypter_image }}"
  sudo: True
  when: galaxy_extras_ie_fetch_jupyter

- name: "Install RStudio container."
  shell: "docker pull {{ galaxy_extras_ie_rstudio_image }}"
  sudo: True
  when: galaxy_extras_ie_fetch_rstudio
