- name: Install pip
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - python-pip
  when: galaxy_extras_install_packages

- name: Install SLURM system packages
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - munge
    - slurm-llnl
    - slurm-llnl-torque 
    - slurm-drmaa-dev
    - python-psutil
  when: galaxy_extras_install_packages

- name: Create Munge Key
  command: /usr/sbin/create-munge-key

- name: Setup Munge
  shell: "mkdir -p /var/run/munge && chown root:root /var/lib/munge/ /var/log/munge/ /var/run/munge /etc/munge/ /etc/munge/munge.key"

- name: Setup tmp area for slurm.
  shell: "mkdir /tmp/slurm && chown {{ galaxy_user_name }}:{{ galaxy_user_name }} /tmp/slurm"

- name: Create slurm configuration file
  template: src=configure_slurm.py.j2 dest=/usr/sbin/configure_slurm.py

- name: Check if Galaxy uses eggs or wheels
  stat:
    path: "{{ galaxy_root }}/lib/galaxy/dependencies/requirements.txt"
  register: requirements_txt

- name: Fetch DRMAA egg for Galaxy
  shell: "{{ galaxy_venv_dir }}/bin/python {{ galaxy_root }}/scripts/fetch_eggs.py -e drmaa -c {{ galaxy_config_file }}"
  when: not requirements_txt.stat.exists

# If job_conf.xml is installed before running galaxyprojectdotorg.galaxy, this would already be installed.
- name: Fetch DRMAA wheel for Galaxy
  pip:
    name: "drmaa"
    extra_args: "--index-url https://wheels.galaxyproject.org/simple/"
    virtualenv: "{{ galaxy_venv_dir }}"
  environment:
    PYTHOPATH: null
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: requirements_txt.stat.exists

- name: "Install Galaxy job conf"
  template: src=job_conf.xml.j2 dest={{galaxy_job_conf_path}}
