
- name: Install web related system packages
  apt: pkg={{ item }} state={{ galaxy_extras_apt_package_state }}
  with_items:
    - uwsgi
    - uwsgi-plugin-python
    - supervisor
  when: galaxy_extras_install_packages

- name: Create Galaxy configuration file
  template: src=supervisor.conf.j2 dest={{ supervisor_conf_path }}

- name: Stop supervisor
  service: name=supervisor state=stopped

- name: Stop services before removing them.
  service: name={{ item }} state=stopped enabled=no
  with_items:
  - nginx
  - uwsgi
  - proftpd
  - munge

- name: Stop services before removing them.
  service: name={{ item }} state=stopped enabled=no
  with_items:
  - slurm-llnl
  when: ansible_distribution_version <= "15.04"

- name: Stop services before removing them.
  service: name={{ item }} state=stopped enabled=no
  with_items:
  - slurmd
  - slurmctld
  when: ansible_distribution_version > "15.04"

- name: Stop services before removing them.
  service: name={{ item }} state=stopped enabled=no
  with_items:
  - postgresql
  when: supervisor_manage_postgres

- name: Start supervisor
  service: name=supervisor state=started
